org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


## Mod Properties
modId=appliedsorting
modName=Applied Sorting
modLicense=MIT
modGroupId=net.meatwo310.appliedsorting
modAuthors=Meatwo310
modDescription=Enhances the AE2 terminal with configurable ID-based sorting.
modDisplayUrl=https://github.com/Meatwo310/applied-sorting/
modIssueTrackerUrl=https://github.com/Meatwo310/applied-sorting/issues
modCredits=Many thanks to TeamAppliedEnergistics for developing Applied Energistics 2. Thanks to mochi-753 for the initial 1.21.1 port.


## Fabric Mod Properties
modFabricEnvironment=*
modFabricEntrypoint=net.meatwo310.appliedsorting.ModMain
modFabricClientEntrypoint=net.meatwo310.appliedsorting.client.ModClient
